import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import vue from 'eslint-plugin-vue';
import vueParser from 'vue-eslint-parser';
import { defineConfig } from 'eslint/config';

export default defineConfig([
	js.configs.recommended,
	...tseslint.configs.recommended,
	vue.configs['flat/recommended'],
	{
		files: ['**/*.{js,ts,vue}'],
		languageOptions: {
			parser: vueParser,
			parserOptions: {
				parser: tseslint.parser,
				ecmaVersion: 'latest',
				sourceType: 'module',
			},
			globals: globals.browser,
		},
		rules: {
			'@typescript-eslint/no-empty-object-type': 'off',
			'@typescript-eslint/no-explicit-any': 'off',
			'@typescript-eslint/no-unused-vars': 'off',
			'@typescript-eslint/no-unused-expressions': 'off',
			'@typescript-eslint/ban-types': 'off',
			'@typescript-eslint/no-dynamic-delete': 'off',
			'vue/no-multiple-template-root': 'off',
			'vue/prop-name-casing': 'off',
			'vue/no-v-html': 'off',
			'vue/no-side-effects-in-computed-properties': 'off',
			'vue/multi-word-component-names': 'off',
			'vue/component-definition-name-casing': ['error', 'PascalCase'],
			'vue/component-name-in-template-casing': ['error', 'PascalCase', {
				'registeredComponentsOnly': false,
			}],
			'vue/custom-event-name-casing': ['error', 'kebab-case'],
			'vue/html-indent': ['error', 'tab', {
				'attribute': 1,
				'baseIndent': 1,
				'closeBracket': 0,
				'alignAttributesVertically': true,
				'ignores': [],
			}],
			'vue/html-closing-bracket-newline': ['error', { 'singleline': 'never', 'multiline': 'always' }],
			'vue/script-indent': ['error', 'tab', { 'switchCase': 1 }],
			'vue/no-v-for-template-key': 'off',
			'no-undef': 'off',

			'quotes': ['error', 'single'],
			'semi': ['error', 'always'],
			'quote-props': 'off',
			'comma-dangle': ['error', {
				'arrays': 'always-multiline',
				'objects': 'always-multiline',
				'imports': 'always-multiline',
				'exports': 'always-multiline',
				'functions': 'never',
			}],
			'no-useless-scape': 'off',
			'no-control-regex': 'off',
			'comma-spacing': ['error'],
			'no-var': 'error',
			'no-unused-vars': 'off',
			'prefer-const': 'error',
			'eqeqeq': ['error', 'smart'],
			'no-template-curly-in-string': 'error',
			'no-duplicate-imports': 'error',
			'default-param-last': ['error'],
			'array-element-newline': ['error', 'consistent'],
			'arrow-spacing': ['error'],
			'block-spacing': ['error'],
			'brace-style': ['error'],
			'function-call-argument-newline': ['error', 'consistent'],
			'jsx-quotes': ['error', 'prefer-double'],
			'key-spacing': ['error', { 'mode': 'strict' }],
			'keyword-spacing': ['error'],
			'no-multiple-empty-lines': ['error', { 'max': 1 }],
			'no-trailing-spaces': ['error', { 'ignoreComments': true }],
			'no-whitespace-before-property': ['error'],
			'object-curly-newline': ['error', { 'consistent': true }],
			'object-curly-spacing': ['error', 'always'],
			'operator-linebreak': ['error', 'after'],
			'rest-spread-spacing': ['error'],
			'space-before-blocks': ['error'],
			'space-before-function-paren': 'off',
			'space-in-parens': ['error', 'never'],
			'space-infix-ops': ['error'],
			'template-curly-spacing': ['error', 'never'],
			'camelcase': 'off',
			'import/no-duplicates': 'off',
			'indent': ['error', 'tab', { 'SwitchCase': 1, 'ignoredNodes': ['ConditionalExpression'] }],
			'no-constant-binary-expression': 'off',
			'no-tabs': 'off',
			'no-console': ['warn', { 'allow': ['error'] }],
			'no-debugger': ['error'],
			'no-extra-boolean-cast': 'off',
			'n/no-callback-literal': 'off',
		},
	},
]);
